# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/sketch_rnn/02_model.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/sketch_rnn/02_model.ipynb 4
from typing import Optional, Tuple

import torch
import torch.nn as nn

from .layers import *

# %% ../../nbs/sketch_rnn/02_model.ipynb 5
#| export


# %% ../../nbs/sketch_rnn/02_model.ipynb 6
#| export

