# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/singleline_models',
                'doc_host': 'https://andrewlook.github.io',
                'git_url': 'https://github.com/andrewlook/singleline_models',
                'lib_path': 'singleline_models'},
  'syms': {'singleline_models.core': {'singleline_models.core.foo': ('core.html#foo', 'singleline_models/core.py')}}}
